config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  root :to => 'home#index'

  get 'music/get-artist/:id' => 'music/artists#proxy_artist', as: :proxy_artist
  get 'music/artists/:slug' => 'music/artists#show', as: :show_artist
  get 'music/all-artists/:wildcard(/:page)' => 'music/artists#alphabetic_index', as: :get_alphabetic_artists
  get 'music/featured-artists(/:page)(/:offset)' => 'music/artists#featured_index', as: :get_featured_artists
  get 'music/artists/:slug/albums/:id' => 'music/artists#album_tracks', as: :show_album_tracks

  get  'music/setlists' => 'music/setlists#index', as: :all_setlists
  get  'music/setlists/:slug' => 'music/setlists#show_all', as: :artist_setlists
  get  'music/setlists/:slug/:id' => 'music/setlists#show', as: :show_setlist
  get  'music/artist-setlist/:slug/:id/:setlist_slug' => 'music/setlists#show_public', as: :show_public_setlist
  get  'music/setlist/new/:slug' => 'music/setlists#new', as: :new_setlist
  post 'music/setlist/new/:slug' => 'music/setlists#create', as: :create_setlist
  get  'music/setlist/set-songs/:slug/:id' => 'music/setlists#set_songs', as: :set_setlist
  post 'music/setlist/set-songs' => 'music/setlists#add_song', as: :add_song
  post 'music/setlist/order-songs' => 'music/setlists#order_songs', as: :order_songs
  get  'music/setlist/get-songs/:id' => 'music/setlists#get_songs', as: :get_current_songs
  post 'music/setlist/remove-song' => 'music/setlists#remove_song', as: :remove_song
  post 'music/setlist/remove-all-songs' => 'music/setlists#remove_all_songs', as: :remove_all_songs

  get  'music/stages/new' => 'geo/stage/stage#new', as: :new_stage
  post 'music/stages/new' => 'geo/stage/stage#create', as: :create_stage
  get  'music/all-stages/:wildcard(/:page)' => 'geo/stage/stage#alphabetic_index', as: :get_alphabetic_stages
  get  'music/stage/:slug(/:page)(/:offset)' => 'geo/stage/stage#show', as: :show_stage

  get  'music/festivals/new'    => 'music/festivals#new', as: :new_festival
  post 'music/festivals/create' => 'music/festivals#create', as: :create_festival
  get  'music/all-festivals/:wildcard(/:page)(/:offset)' => 'music/festivals#alphabetic_index', as: :get_alphabetic_festivals
  get  'music/festival/:slug'   => 'music/festivals#show', as: :show_festival
  get  'music/festival/:slug/artists'   => 'music/festivals#set_artists', as: :set_festival_artists

  get  'api/me/artists' => 'api/v1/me/me#my_artists', as: :api_v1_my_artists
  get  'api/me/playlists' => 'api/v1/me/me#my_playlists', as: :api_v1_my_playlists

  get  'api/setlists(/:page)(/:offset)' => 'api/v1/music/setlist/setlists#index', as: :api_v1_setlists
  get  'api/stage-setlists/:slug(/:page)(/:offset)' => 'api/v1/music/setlist/setlists#setlists_by_stage', as: :api_v1_setlists_by_stage
  get  'api/featured_artists(/:page)(/:offset)' => 'api/v1/music/artist/artists#featured_index', as: :api_v1_artists
  get  'api/alphabetic_artists/:wildcard(/:page)(/:offset)' => 'api/v1/music/artist/artists#alphabetic_index', as: :api_v1_alphabetic_artists
  get  'api/autocomplete_artists/:wildcard(/:page)(/:offset)' => 'api/v1/music/artist/artists#autocomplete', as: :api_v1_autocomplete_artists
  get  'api/artist_albums/:id(/:page)(/:offset)' => 'api/v1/music/artist/artists#artist_albums', as: :api_v1_artist_albums
  get  'api/artist_tracks/:id(/:page)(/:offset)' => 'api/v1/music/artist/artists#artists_tracks', as: :api_v1_artist_tracks

  get  'api/geo/search-stages/:wildcard(/:page)(/:offset)' => 'api/v1/geo/stage#search', as: :api_v1_search_stage 
  get  'api/geo/featured-stages(/:page)(/:offset)' => 'api/v1/geo/stage#featured_stages', as: :api_v1_featured_stages

  get  'api/util/countries' => 'api/v1/util/country#index', as: :api_v1_countries

  get  'api/search-festivals/:wildcard(/:page)(/:offset)' => 'api/v1/music/festival/festivals#search', as: :api_v1_search_festival
  get  'api/featured-festivals(/:page)(/:offset)' => 'api/v1/music/festival/festivals#featured_index', as: :api_v1_featured_festivals

  get 'ads/artist_skyscraper' => 'ads/backup_ad#artist_skyscraper', as: :artist_skyscraper_ad 

    get '404', :to => "web/error#show_400", :code => 404

    get '500', :to => "web/error#show_500", :code => 500

end

app/models/music.rb
module Music
  def self.table_name_prefix
    'music_'
  end
end

app/models/music/album.rb
class Music::Album < ActiveRecord::Base
  belongs_to :artist, class_name: "Music::Artist", foreign_key: "music_artist_id"

  has_many :tracks, class_name: "Music::Track", foreign_key: "music_album_id"

end

app/models/music/festival.rb
class Music::Festival < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :logo, Music::FestivalUploader

  def self.search(search, page = 1 , offset = 10)
    wildcard_search = "%#{search}%"

    where("name ILIKE ?", wildcard_search)
      .order(start_date: :desc)
      .page(page)
      .per(offset)
  end 

  
  def self.search_count(search)
    wildcard_search = "%#{search}%"

    where("name ILIKE ?", wildcard_search).count
  end 

end

app/controllers/api/v1/music/artist/artists_controller.rb
class Api::V1::Music::Artist::ArtistsController < ApplicationController
  require 'uri'
 
  def featured_index
    page = params[:page].blank? ? 1 : params[:page].to_i
    offset = params[:offset].blank? ? 10 : params[:offset].to_i

    artists_data = Array.new
    artists = Rails.cache.fetch("#{page}_#{offset}/artists", expires_in: 10.minutes) do
      ::Music::Artist.order_by_rand.all.page(page).per(offset)
    end  

    artists.each do |artist|
      #social_artist =  Music::ArtistsManager.get_artist(@access_token, {id:artist.spotify_id})  
      social_artist  = Rails.cache.fetch("#{artist.spotify_id}/artist", expires_in: 1440.minutes) do
        Music::ArtistsManager.get_artist(@access_token, {id: artist.spotify_id}) 
      end  
      artists_data.push({
          artist: artist,
          social_data: social_artist
        })
    end  

    render json: artists_data, status: 200
    expires_in 3600.seconds, :public => true
  end

  def autocomplete
    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 10 : params[:offset].to_i

    artists_data = Array.new
    artists = Rails.cache.fetch("#{params[:wildcard]}_#{@page}_#{@offset}/auto_artists", expires_in: 10.minutes) do
      #::Music::Artist.search(params[:wildcard], page, offset)
      ::Music::ArtistsManager.get_artists_by_wildcard(@access_token, {wildcard:  URI.escape(params[:wildcard]), limit: @offset, offset: (@page -1) * @offset})
    end  

    artists['artists']['items'].each do |artist| 
      artists_data.push(artist)
    end  

    render json: artists_data, status: 200
    expires_in 3600.seconds, :public => true
  end



  def alphabetic_index
    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 20 : params[:offset].to_i
    
    @artists = Rails.cache.fetch("#{params[:wildcard]}_#{@page}_#{@offset}/artists", expires_in: 1440.minutes) do
      ::Music::ArtistsManager.get_artists_by_wildcard(@access_token, {wildcard:  params[:wildcard], limit: @offset, offset: (@page -1) * @offset})
    end

    render json: @artists, status: 200
    expires_in 1440.minutes, :public => true
  end

  def artist_albums
     @page = params[:page].blank? ? 1 : params[:page].to_i
     @offset = params[:offset].blank? ? 20 : params[:offset].to_i

     @albums = Rails.cache.fetch("#{params[:id]}/artist_albums", expires_in: 1440.minutes) do
        @artist = ::Music::Artist.find_by(spotify_id: params[:id])
        if ::Music::Album.where(artist: @artist).blank? &&  !@access_token.nil?
          ::Music::ArtistsManager.artist_albums(@access_token, {id: params[:id], limit: @offset, offset: (@page -1) * @offset})
        else
          items = Array.new
          albums = Music::Album.where(artist: @artist).page(@page).per(@offset)
          albums.each do |album_data|
            items.push({
               id: album_data.spotify_id,
               images: [{url: album_data.image_high}, {url: album_data.image_medium}, {url: album_data.image}],
               name: album_data.name
            })
          end 
          {items: items} 
        end  
     end  

     render json: @albums, status: 200
     expires_in 1440.minutes, :public => true 
  end  

  def artists_tracks
    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 20 : params[:offset].to_i

    album_tracks = Array.new

    @albums = Rails.cache.fetch("#{params[:id]}/artist_albums", expires_in: 1440.minutes) do
        ::Music::ArtistsManager.artist_albums(@access_token, {id: params[:id], limit: @offset, offset: (@page -1) * @offset})
    end  

    @albums['items'].each do |album|
      tracks = Rails.cache.fetch("#{album['id']}/album_tracks", expires_in: 1440.minutes) do
        ::Music::TracksManager.get_album_tracks(@access_token, {id: album['id']})
      end 

      album_tracks.push({album: album, tracks: tracks})
    end   

    render json: album_tracks, status: 200
    expires_in 1440.minutes, :public => true 
  end  


end  

app/controllers/api/v1/music/festival/festivals_controller.rb
class Api::V1::Music::Festival::FestivalsController < ApplicationController

  def search
    autcomplete_data = Array.new

    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 10 : params[:offset].to_i

    @festivals  = Rails.cache.fetch("#{params[:wildcard]}_#{@page}_#{@offset}/festivals", expires_in: 10.minutes) do
      ::Music::Festival.search(params[:wildcard], @page, @offset)
    end

    @festivals.each do |festival|
      autcomplete_data.push({
        id: festival.id,
        name: "#{festival.name} - #{festival.country}",
        logo: festival.logo,
        country: festival.country,
        slug: festival.slug 
      })
    end  

    render json: autcomplete_data, status:200
    expires_in 60.seconds, :public => true
  end 

  def featured_index

    autcomplete_data = Array.new

    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 10 : params[:offset].to_i

    @festivals  = Rails.cache.fetch("#{@page}_#{@offset}/featured_festivals", expires_in: 30.minutes) do
      ::Music::Festival.order_by_rand.all.order(start_date: :desc).page(@page).per(@offset)
    end

    @festivals.each do |festival|
      autcomplete_data.push({
        id: festival.id,
        name: "#{festival.name} - #{festival.country}",
        logo: festival.logo,
        country: festival.country,
        slug: festival.slug 
      })
    end  

    render json: autcomplete_data, status:200
    expires_in 60.seconds, :public => true

  end  

end  

app/controllers/api/v1/music/setlist/setlists_controller.rb
class Api::V1::Music::Setlist::SetlistsController < ApplicationController
  skip_before_filter :set_client, :set_user, :set_refresh_token, :set_token, :set_api_client, :set_my_artists, :set_playlists

  def index
    page = params[:page].blank? ? 1 : params[:page].to_i
    offset = params[:offset].blank? ? 10 : params[:offset].to_i

    @setlists = ::Music::Setlist.all.order(set_date: :desc).page(page).per(offset)

    setlists_data = Array.new

    @setlists.each do |setlist|
      setlists_data.push({
        setlist: setlist,
        artist: setlist.artist,
        stage: setlist.stage.nil? ? nil : setlist.stage
      })
    end  

    render json: setlists_data, status: 200
    expires_in 60.seconds, :public => true
  end

  def setlists_by_stage

    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 20 : params[:offset].to_i

    @stage = Rails.cache.fetch("#{params[:slug]}/stage", expires_in: 60.minutes) do
       ::Geo::Stage.find_by(slug: params[:slug])
    end

    @setlists = Rails.cache.fetch("#{params[:slug]}_#{@page}_#{@offset}/setlists", expires_in: 10.minutes) do
      ::Music::Setlist.where(stage: @stage).order(set_date: :desc).page(@page).per(@offset)
    end  

    setlists_data = Array.new

    @setlists.each do |setlist|
      setlists_data.push({
        setlist: setlist,
        artist: setlist.artist,
        stage: @stage
      })
    end  

    render json: setlists_data, status: 200
    expires_in 600.seconds, :public => true

  end  

  

end  

app/controllers/cms/music/artists_controller.rb
class Cms::Music::ArtistsController < ApplicationController

  


end  

app/controllers/music/artists_controller.rb
class Music::ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :album_tracks]
  before_action :set_social_artist, only: [:show]
  before_action :set_tracks, only: [:show]
  before_action :set_artists, only: [:alphabetic_index]
  before_action :set_featured_artists, only: [:featured_index]
  before_action :set_artists_by_spotify_id, only: [:proxy_artist]

  def show
    @setlists = Music::Setlist.where(artist: @artist).order(set_date: :desc).page(1).per(5)

      @page = 1
      @offset = 20
      @albums = Rails.cache.fetch("#{@artist.spotify_id}/artist_albums", expires_in: 140.minutes) do
        Music::ArtistsManager.artist_albums(@access_token, {id: @artist.spotify_id, limit: @offset, offset: (@page -1) * @offset})
      end

      @artist.image_ultra   = @social_artist['images'][0].nil? ?  nil : @social_artist['images'][0]['url']
      @artist.image_high    = @social_artist['images'][1].nil? ?  nil : @social_artist['images'][1]['url']
      @artist.image_medium  = @social_artist['images'][2].nil? ?  nil : @social_artist['images'][2]['url']
      @artist.image_base    = @social_artist['images'][3].nil? ?  nil : @social_artist['images'][3]['url']
      @artist.save


    @feat_tracks = Rails.cache.fetch("#{@artist.spotify_id}/artist_featured_tracks", expires_in: 140.minutes) do
      #Music::Track.order_by_rand.where('music_album_id IN (?)', @albums_data.map{|x| x.id}).page(1).per(10)
      Music::ArtistsManager.artist_top_tracks(@access_token, {id: @artist.spotify_id})
    end

    #@related_artists = @artist.set_related_artists(@access_token)
    @related_artists = Rails.cache.fetch("#{@artist.spotify_id}/related_artists", expires_in: 140.minutes) do
      Music::ArtistsManager.related_artists(@access_token, {id: @artist.spotify_id})
    end

    expires_in 30.minutes, :public => true, 'max-stale' => 0 unless current_user
  end

  def proxy_artist

    @artist = Music::Artist.find_by(spotify_id: params[:id])

    if @artist.blank?
      @artist = Music::ArtistsManager.create_artist(@access_token, {id:  params[:id]})

      redirect_to show_artist_path(slug: @artist.slug)
    else
      redirect_to show_artist_path(slug: @artist.slug)
    end

    expires_in 1440.minutes, :public => true

  end

  def alphabetic_index

      expires_in 10.minutes, :public => true

  end

  def featured_index

    expires_in 10.minutes, :public => true
  end

  def album_tracks

    @album = Rails.cache.fetch("#{params[:id]}/album", expires_in: 140.minutes) do
      Music::TracksManager.get_album(@access_token, {id: params[:id]})
    end

    @album_tracks = Rails.cache.fetch("#{params[:id]}/albums_tracks", expires_in: 140.minutes) do
      Music::TracksManager.get_album_tracks(@access_token, {id: params[:id]})
    end

    @albums = Rails.cache.fetch("#{@artist.spotify_id}/artist_albums", expires_in: 140.minutes) do
       Music::ArtistsManager.artist_albums(@access_token, {id: @artist.spotify_id, limit: 10, offset: 0})
    end

    expires_in 30.days, :public => true
  end


  #private stuff
  private

    def set_artists_by_spotify_id
      @artist = Rails.cache.fetch("#{params[:id]}/artist", expires_in: 1440.minutes) do
        Music::Artist.find_by(spotify_id: params[:id])
      end
    end

    def set_artists
      @page = 1
      @offset = 20

      if !params[:page].nil?
        @page = params[:page].to_i
      end

      @artists = Rails.cache.fetch("#{params[:wildcard]}_#{@page}_#{@offset}/artists", expires_in: 1440.minutes) do
        Music::ArtistsManager.get_artists_by_wildcard(@access_token, {wildcard:  params[:wildcard], limit: @offset, offset: (@page -1)*@offset})
      end
    end

    def set_featured_artists
      @page = params[:page].blank? ? 1 : params[:page].to_i
      @offset = params[:offset].blank? ? 20 : params[:offset].to_i

      @featured_artists = Rails.cache.fetch("#{@page}_#{@offset}/artists", expires_in: 10.minutes) do
        ::Music::Artist.all.page(@page).per(@offset)
      end

      @all_artists = Rails.cache.fetch("all_artists", expires_in: 0.minutes) do
        ::Music::Artist.all.count
      end
    end

    def set_artist
      @artist = Rails.cache.fetch("#{params[:slug]}/artist", expires_in: 1440.minutes) do
        Music::Artist.find_by(slug: params[:slug])
      end

      if @artist.nil?
        @artist = Music::ArtistsManager.create_artist(@access_token, {id:  params[:slug]})
        @artist = Rails.cache.fetch("#{params[:slug]}/artist_by_spotifynx", expires_in: 1440.minutes) do
          Music::Artist.find_by(spotify_id: params[:slug])
        end
        puts "FIND BY"
        puts @artist.spotify_id
        if @artist.nil?
          redirect_to '/404'
        end
      end
    end

    def set_social_artist
      if !@artist.nil?
        @social_artist = Rails.cache.fetch("#{@artist.spotify_id}/social_artist", expires_in: 1440.minutes) do
          Music::ArtistsManager.get_artist(@access_token, {id:@artist.spotify_id})
        end
      end
    end

    def set_tracks
      if !@artist.nil?
        @tracks = Rails.cache.fetch("#{@artist.spotify_id}/tracks", expires_in: 1440.minutes) do
          Music::ArtistsManager.artist_top_tracks(@access_token, {id: @artist.spotify_id})
        end
      end
    end

end

app/views/music/festivals/alphabetic_index.haml
= render partial: 'shared/metatags',
  locals: { the_title: "Music Festivals by #{params[:wildcard][0,1].upcase}",
  the_description: "Check your favorite music festivals by #{params[:wildcard][0,1].upcase} letter",
  the_keywords: ['music', 'festivals', 'tours'],
  the_image: "",
  the_url: request.original_url }


- items = [{caption: 'Home', link: "/"}, {caption: 'Festivals', link: ''}, {caption: params[:wildcard], link: ""}]
  
.row
  .col.s12.m12.l12
    .card
      .card-content
        
        = render partial: "shared/breadcrumb", locals: {items: items}

        - if !@festivals.blank? 
          %ul.pagination
            - ('A'..'Z').each do |wildcard|
              - if wildcard == params[:wildcard][0,1].upcase
                %li.ten-margin-bot.active
                  %a{:href => get_alphabetic_festivals_path(wildcard: wildcard), data: { no_turbolink: true }}
                    = wildcard   
              - else
                %li.ten-margin-bot.waves-effect
                  %a{:href => get_alphabetic_festivals_path(wildcard: wildcard), data: { no_turbolink: true }}
                    = wildcard

          = paginate @festivals

          .row      
            %h4
              = "Results for \"#{params[:wildcard]}\"" 
              .chip
                - if !@festivals_count.nil?  
                  = @festivals_count
                - else
                  0

            %span#wildcard{style: "display:none"}
              = params[:wildcard] 

            %span#page{style: "display:none"}
              = @page 

            %span#offset{style: "display:none"}
              = @offset

            - if !@festivals.blank? 
              #festivals
                - @festivals.each do |festival|
                  - #show_festival_path(slug: festival.slug)
            - else
              No results      

app/views/music/festivals/new.haml
- items = [{caption: 'Home', link: "/"}, 
  {caption: 'New festival', link: ''}]

.row
  .col.s12.m7.l8
    .card
      .card-content
        = render partial: "shared/breadcrumb", locals: {items: items}

        %h4
          = "New Festival"

        = form_for @festival, :as => 'festival_data', :url => create_festival_path, :html => {:multipart => true}, :method => :POST do |f|
          .row.no-margin-bot
            .input-field.col.s12
              = f.label :name, class: "col-lg-2 control-label"
              %br/
              = f.text_field :name, class: "validate"

          .row.no-margin-bot    
            .input-field.col.s12
              = f.label "From", class: "col-lg-2 control-label"
              %br/
              = f.date_field :start_date, class: "datepicker" 

          .row.no-margin-bot    
            .input-field.col.s12
              = f.label "To", class: "col-lg-2 control-label"
              %br/
              = f.date_field :end_date, class: "datepicker"    

          .row
            .input-field.col.s12   
              = f.label :country, class: 'col-lg-2 control-label'
              %br/ 
              %br/
              - countries_array = @countries.map { |country| [country, country] }  
              = select_tag "festival_data[country]", options_for_select(@countries.collect {|p| [ p, p ] }), class: 'browser-default'
          .row
            .input-field.col.s12   
              = f.label :logo, class: 'col-lg-2 control-label'
              %br/ 
              %br/   
              = f.hidden_field(:logo_cache)
              = f.file_field(:logo)
            
          .row
            .input-field.col.s12
              = f.submit "Save" , class: "waves-effect waves-light btn grey darken-4" 

= javascript_include_tag "jquery.easy-autocomplete", :type=> "text/javascript" 

:javascript

  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year
    format: 'dd/mm/yyyy'
  });

  $( document ).ready(function() {  
      var options = {
        url: function(phrase) {
           return "/api/search-festivals/" + phrase;
        },
        getValue: "name",
        list: {
            onChooseEvent: function() {
            console.log("Selected " + $("#festival_data_name").val());
            Materialize.toast('Stage already exists', 3000, 'rounded')
          },
          match: {enabled: true}
        }
      };    
      $("#festival_data_name").easyAutocomplete(options);
  });

app/views/music/festivals/set_artists.haml
- meta_image =  @festival.logo.nil? ? "" : @festival.logo

= render partial: 'shared/metatags',
  locals: { the_title: "Festivals - #{@festival.name}",
  the_description: "Set #{@festival.name} artists",
  the_keywords: [@festival.name],
  the_image: meta_image,
  the_url: request.original_url }

- items = [{caption: 'Home', link: "/"}, 
  {caption: 'Festivals', link: ''},
  {caption: @festival.name[0,1].upcase , link: get_alphabetic_festivals_path(wildcard: @festival.name[0,1].upcase)},
  {caption: "#{@festival.name} artists" , link: ""}]


.row
  .col.s12.m7.l8
    .card
      .card-content
        = render partial: "shared/breadcrumb", locals: {items: items}

        %h5
          Search Artists

        = form_for @festival, :as => 'festival_data', :url => "", :html => {:multipart => true}, :method => :POST do |f|
          .row.no-margin-bot
            .input-field.col.s12
              = f.label "Artist", class: "col-lg-2 control-label"
              %br/
              = text_field_tag "artist_name", nil, class: "validate" 

          .row
            .input-field.col.s12
              %a#search_btn.btn.waves-effect.waves-light.light-blue.base.five-margin-bot
                Search   

        %ul#items.collection.with-header           


= javascript_include_tag "jquery.easy-autocomplete", :type=> "text/javascript" 

:javascript

  $( document ).ready(function() {  
      var options = {
        url: function(phrase) {
           return "/api/autocomplete_artists/" + phrase;
        },
        getValue: "name",
        requestDelay: 500,
        list: {
            onChooseEvent: function() {
            console.log("Selected " + $("#artist_name").val());
            console.log("data "+ $("#artist_name").getSelectedItemData().name);
            //Materialize.toast('Stage already exists', 3000, 'rounded')
          },
          match: {enabled: true}
        }
      };    
      $("#artist_name").easyAutocomplete(options);
  });

  $( "#search_btn" ).click(function() {
    
    var keyword = $("#artist_name").val();
    var list = $('#items');
    list.empty();

    console.log("searching by " + keyword)

    $.ajax({
      url: "/api/autocomplete_artists/" + keyword,
      dataType: 'json',
      cache: false,
      success: function(data) {
        console.log(data);

        var li = $('<li/>').addClass('collection-header').html("<h5>Results</h5>").appendTo(list);
        data.forEach( function (item)
        {
            var image_src = "/images/default_artist.png";
            //console.log("images " + item.images[2].url);

            if(item.images[2] !== undefined){
              image_src = item.images[2].url;
            }

            var img = "<img class='circle valign' src='" + image_src + "' width='45' height='45'/>";
            var caption ="<span class='valign' style='margin-left:10px'>"+ item.name +"</span>";

            var li = $('<li/>').addClass('collection-item valign-wrapper').html(img + " " + caption).appendTo(list);
        });

      },
      error: function(xhr, status, err) {
        console.error("oooo");
      }
    });

  });

app/views/music/festivals/show.haml
- meta_image =  @festival.logo.nil? ? "" : @festival.logo

= render partial: 'shared/metatags',
  locals: { the_title: "Festivals - #{@festival.name}",
  the_description: "Check #{@festival.name} setlists and artists",
  the_keywords: [@festival.name],
  the_image: meta_image,
  the_url: request.original_url }

- items = [{caption: 'Home', link: "/"}, 
  {caption: 'Festivals', link: ''},
  {caption: @festival.name[0,1].upcase , link: get_alphabetic_festivals_path(wildcard: @festival.name[0,1].upcase)},
  {caption: @festival.name , link: ""}]

.row
  .col.s12.m12.l12
    = render partial: "shared/breadcrumb", locals: {items: items}

.row
  .col.s12.m7.l8
    .card
      .card-content
        %h4
          %span
            = @festival.name.capitalize

    .card
      .card-content
        %span.card-title Artists
        - if !current_user.nil? 
          %a.btn-floating.waves-effect.waves-light.blue-grey.base{href: set_festival_artists_path(slug: @festival.slug), data: { no_turbolink: true }}
            %i.material-icons.light-blue.base> add      



  .col.s12.m5.l4
    .card
      .card-content
        %span.card-title
          Other Festivals
        #festivals
          .progress
            .indeterminate.light-blue
      .card-action
        %a{href: get_alphabetic_festivals_path(wildcard: 'a'), data: { no_turbolink: true }}
          More      

    

    .card
      .card-content
        %span.card-title
          Featured stages
        #stages
          .progress
            .indeterminate.light-blue
            
      .card-action
        %a{href: get_alphabetic_stages_path(wildcard: 'a'), data: { no_turbolink: true }}
          More

%script{:type => "application/ld+json"}
  {
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "#{@festival.name.capitalize}",
  "startDate" : "#{@festival.start_date.strftime('%F')}",
  "endDate": "#{@festival.end_date.strftime('%F')}",
  "url" : "#{request.original_url}",
  "location" : {
  "@type" : "Place",
  "name" : "#{@festival.country}",
  "address": "#{@festival.country}"
  }
  }


= javascript_include_tag "music/festival/featured_festivals", :type=> "text/babel"
= javascript_include_tag "music/geo/featured_stages", :type=> "text/babel" 