config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  root :to => 'home#index'

  get 'music/get-artist/:id' => 'music/artists#proxy_artist', as: :proxy_artist
  get 'music/artists/:slug' => 'music/artists#show', as: :show_artist
  get 'music/all-artists/:wildcard(/:page)' => 'music/artists#alphabetic_index', as: :get_alphabetic_artists
  get 'music/featured-artists(/:page)(/:offset)' => 'music/artists#featured_index', as: :get_featured_artists
  get 'music/artists/:slug/albums/:id' => 'music/artists#album_tracks', as: :show_album_tracks

  get  'music/setlists' => 'music/setlists#index', as: :all_setlists
  get  'music/setlists/:slug' => 'music/setlists#show_all', as: :artist_setlists
  get  'music/setlists/:slug/:id' => 'music/setlists#show', as: :show_setlist
  get  'music/artist-setlist/:slug/:id/:setlist_slug' => 'music/setlists#show_public', as: :show_public_setlist
  get  'music/setlist/new/:slug' => 'music/setlists#new', as: :new_setlist
  post 'music/setlist/new/:slug' => 'music/setlists#create', as: :create_setlist
  get  'music/setlist/set-songs/:slug/:id' => 'music/setlists#set_songs', as: :set_setlist
  post 'music/setlist/set-songs' => 'music/setlists#add_song', as: :add_song
  post 'music/setlist/order-songs' => 'music/setlists#order_songs', as: :order_songs
  get  'music/setlist/get-songs/:id' => 'music/setlists#get_songs', as: :get_current_songs
  post 'music/setlist/remove-song' => 'music/setlists#remove_song', as: :remove_song
  post 'music/setlist/remove-all-songs' => 'music/setlists#remove_all_songs', as: :remove_all_songs

  get  'music/stages/new' => 'geo/stage/stage#new', as: :new_stage
  post 'music/stages/new' => 'geo/stage/stage#create', as: :create_stage
  get  'music/all-stages/:wildcard(/:page)' => 'geo/stage/stage#alphabetic_index', as: :get_alphabetic_stages
  get  'music/stage/:slug(/:page)(/:offset)' => 'geo/stage/stage#show', as: :show_stage

  get  'music/festivals/new'    => 'music/festivals#new', as: :new_festival
  post 'music/festivals/create' => 'music/festivals#create', as: :create_festival
  get  'music/all-festivals/:wildcard(/:page)(/:offset)' => 'music/festivals#alphabetic_index', as: :get_alphabetic_festivals
  get  'music/festival/:slug'   => 'music/festivals#show', as: :show_festival
  get  'music/festival/:slug/artists'   => 'music/festivals#set_artists', as: :set_festival_artists

  get  'api/me/artists' => 'api/v1/me/me#my_artists', as: :api_v1_my_artists
  get  'api/me/playlists' => 'api/v1/me/me#my_playlists', as: :api_v1_my_playlists

  get  'api/setlists(/:page)(/:offset)' => 'api/v1/music/setlist/setlists#index', as: :api_v1_setlists
  get  'api/stage-setlists/:slug(/:page)(/:offset)' => 'api/v1/music/setlist/setlists#setlists_by_stage', as: :api_v1_setlists_by_stage
  get  'api/featured_artists(/:page)(/:offset)' => 'api/v1/music/artist/artists#featured_index', as: :api_v1_artists
  get  'api/alphabetic_artists/:wildcard(/:page)(/:offset)' => 'api/v1/music/artist/artists#alphabetic_index', as: :api_v1_alphabetic_artists
  get  'api/autocomplete_artists/:wildcard(/:page)(/:offset)' => 'api/v1/music/artist/artists#autocomplete', as: :api_v1_autocomplete_artists
  get  'api/artist_albums/:id(/:page)(/:offset)' => 'api/v1/music/artist/artists#artist_albums', as: :api_v1_artist_albums
  get  'api/artist_tracks/:id(/:page)(/:offset)' => 'api/v1/music/artist/artists#artists_tracks', as: :api_v1_artist_tracks

  get  'api/geo/search-stages/:wildcard(/:page)(/:offset)' => 'api/v1/geo/stage#search', as: :api_v1_search_stage 
  get  'api/geo/featured-stages(/:page)(/:offset)' => 'api/v1/geo/stage#featured_stages', as: :api_v1_featured_stages

  get  'api/util/countries' => 'api/v1/util/country#index', as: :api_v1_countries

  get  'api/search-festivals/:wildcard(/:page)(/:offset)' => 'api/v1/music/festival/festivals#search', as: :api_v1_search_festival
  get  'api/featured-festivals(/:page)(/:offset)' => 'api/v1/music/festival/festivals#featured_index', as: :api_v1_featured_festivals

  get 'ads/artist_skyscraper' => 'ads/backup_ad#artist_skyscraper', as: :artist_skyscraper_ad 

    get '404', :to => "web/error#show_400", :code => 404

    get '500', :to => "web/error#show_500", :code => 500

end

app/models/geo/stage.rb
class Geo::Stage < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :image, Music::StageUploader

  def self.search(search, page = 1 , offset = 10)
    wildcard_search = "%#{search}%"

    where("name ILIKE ?", wildcard_search)
      .page(page)
      .per(offset)
  end 

  def self.search_count(search)
    wildcard_search = "%#{search}%"

    where("name ILIKE ?", wildcard_search).count
  end 

  has_many :setlists, class_name: "Music::Setlist"   

end

app/controllers/api/v1/geo/stage_controller.rb
class Api::V1::Geo::StageController < ApplicationController
  skip_before_filter :set_client, :set_user, :set_refresh_token, :set_token, :set_api_client, :set_my_artists, :set_playlists, :set_featured_tracks  

  def search
    autcomplete_data = Array.new

    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 10 : params[:offset].to_i

    @stages  = Rails.cache.fetch("#{params[:wildcard]}_#{@page}_#{@offset}/stages", expires_in: 10.minutes) do
      ::Geo::Stage.search(params[:wildcard], @page, @offset)
    end

    @stages.each do |stage|
      autcomplete_data.push({
        id: stage.id,
        name: "#{stage.name} - #{stage.country}",
        country: stage.country,
        slug: stage.slug 
      })
    end  

    render json: autcomplete_data, status:200
    expires_in 60.seconds, :public => true
  end 

  def featured_stages 
     @page = params[:page].blank? ? 1 : params[:page].to_i
     @offset = params[:offset].blank? ? 10 : params[:offset].to_i

     @stages  = Rails.cache.fetch("#{@page}_#{@offset}/featured-stages", expires_in: 10.minutes) do
      ::Geo::Stage.order_by_rand.all.page(@page).per(@offset)
     end

     render json: @stages, status:200
     expires_in 60.seconds, :public => true
  end                               
  

end 

app/controllers/geo/stage/stage_controller.rb
class Geo::Stage::StageController < ApplicationController
  skip_before_filter :set_client, :set_user, :set_refresh_token, :set_token, :set_api_client, :set_my_artists, :set_playlists
  before_action :set_stage, only: [:show]
  before_action :set_setlists, only: [:show]

  def show

  end  


  def new
    @stage = Geo::Stage.new 

    @countries  = Rails.cache.fetch("countries", expires_in: 730.hours) do
      ISO3166::Country.all_translated 
    end
  end

  def create
    @stage =  Geo::Stage.where(name: params[:stage_data][:name].split(" - ")[0], country: params[:stage_data][:country]).first

    if @stage.blank?
=begin
      @stage = Geo::Stage.new({
         name: params[:stage_data][:name], country: params[:country]
      })
=end
       @stage = Geo::Stage.new(stage_params)

      @stage.country = params[:country]

      if @stage.save
        redirect_to get_alphabetic_stages_path(wildcard: params[:stage_data][:name][0,1].upcase)  
      else
        redirect_to new_stage_path  
      end  
    else
      redirect_to get_alphabetic_stages_path(wildcard: params[:stage_data][:name][0,1].upcase)  
    end  
  end  

  def stage_params
    params.require(:stage_data).permit(:name, :country, :image, :image_cache)
  end

  def alphabetic_index    
    @page = params[:page].blank? ? 1 : params[:page].to_i
    @offset = params[:offset].blank? ? 20 : params[:offset].to_i

    @stages  = Rails.cache.fetch("#{params[:wildcard]}_#{@page}_#{@offset}/stages", expires_in: 10.minutes) do
      ::Geo::Stage.search(params[:wildcard], @page, @offset)
    end

    @search_count =  Rails.cache.fetch("#{params[:wildcard]}/stages_count", expires_in: 10.minutes) do
      ::Geo::Stage.search_count(params[:wildcard])
    end

    expires_in 10.minutes, :public => true

  end  

  private

    def set_stage
      @stage = Rails.cache.fetch("#{params[:slug]}/stage", expires_in: 1440.minutes) do
        Geo::Stage.find_by(slug: params[:slug])
      end  
    end  

    def set_setlists
      @page = params[:page].blank? ? 1 : params[:page].to_i
      @offset = params[:offset].blank? ? 20 : params[:offset].to_i

      @setlists = Rails.cache.fetch("#{@stage.slug}_#{@page}_#{@offset}/setlists", expires_in: 10.minutes) do
        ::Music::Setlist.where(stage: @stage).order(set_date: :desc).page(@page).per(@offset)
      end  
    end  

end  

app/views/geo/stage/stage/alphabetic_index.haml
- items = [{caption: 'Home', link: "/"}, {caption: 'Stages', link: ''}, {caption: params[:wildcard], link: ''}]

.row
  .col.s12.m12.l12
    .card
      .card-content
        = render partial: "shared/breadcrumb", locals: {items: items}

        - if !@stages.blank? 
          %ul.pagination
            - ('A'..'Z').each do |wildcard|
              - if wildcard == params[:wildcard][0,1].upcase
                %li.ten-margin-bot.active
                  %a{:href => get_alphabetic_stages_path(wildcard: wildcard), data: { no_turbolink: true }}
                    = wildcard   
              - else
                %li.ten-margin-bot.waves-effect
                  %a{:href => get_alphabetic_stages_path(wildcard: wildcard), data: { no_turbolink: true }}
                    = wildcard   

          = paginate @stages  

          .row      
            %h4
              = "Results for \"#{params[:wildcard]}\"" 
              .chip
                - if !@search_count.nil?  
                  = @search_count
                - else
                  0

            %span#wildcard{style: "display:none"}
              = params[:wildcard] 

            %span#page{style: "display:none"}
              = @page 

            %span#offset{style: "display:none"}
              = @offset

            - if !@stages.blank? 
              #stages
                .progress
                  .indeterminate.light-blue 
            - else
              No results      

= javascript_include_tag "music/geo/alphabetic_stages", :type=> "text/babel"

app/views/geo/stage/stage/new.haml
- items = [{caption: 'Home', link: "/"}, 
  {caption: 'New stage', link: ''}]

.row
  .col.s12.m7.l8
    .card
      .card-content
        = render partial: "shared/breadcrumb", locals: {items: items}

        %h4
          = "New stage" 

        = form_for @stage, :as => 'stage_data', :url => create_stage_path, :html => {:multipart => true}, :method => :POST do |f|
          .row.no-margin-bot
            .input-field.col.s12
              = f.label :name, class: "col-lg-2 control-label"
              %br/
              = f.text_field :name, class: "validate"

          .row
            .input-field.col.s12   
              = f.label :image, class: 'col-lg-2 control-label'
              %br/ 
              %br/   
              = f.hidden_field(:image_cache)
              = f.file_field(:image)    

          .row
            .input-field.col.s12   
              = f.label :country, class: 'col-lg-2 control-label'
              %br/ 
              %br/
              - countries_array = @countries.map { |country| [country, country] }  
              = select_tag :country, options_for_select(@countries.collect {|p| [ p, p ] }), class: 'browser-default'
            
          .row
            .input-field.col.s12
              = f.submit "Save" , class: "waves-effect waves-light btn grey darken-4"  

= javascript_include_tag "jquery.easy-autocomplete", :type=> "text/javascript" 

:javascript
  $( document ).ready(function() {  
      var options = {
        url: function(phrase) {
           return "/api/geo/search-stages/" + phrase;
        },
        getValue: "name",
        list: {
            onChooseEvent: function() {
            console.log("Selected " + $("#stage_data_name").val());
            Materialize.toast('Stage already exists', 3000, 'rounded')
          },
          match: {enabled: true}
        }
      };    
      $("#stage_data_name").easyAutocomplete(options);
  });

app/views/geo/stage/stage/show.haml
- meta_image = ""

= render partial: 'shared/metatags',
  locals: { the_title: "#{@stage.name}",
  the_description: "Check concerts in #{@stage.name}",
  the_keywords: [@stage.name],
  the_image: meta_image,
  the_url: request.original_url }

- items = [{caption: 'Home', link: "/"}, 
  {caption: 'Stages', link: ''},
  {caption: @stage.name[0,1] , link: get_alphabetic_stages_path(wildcard: @stage.name[0,1])},
  {caption: @stage.name , link: ""}]

.row
  .col.s12.m7.l8
    .card
      .card-content
        = render partial: "shared/breadcrumb", locals: {items: items}

        %h4
          = @stage.name

        %span#slug{style: "display:none"}
          = @stage.slug  

        %span#page{style: "display:none"}
          = @page

        %span#offset{style: "display:none"}
          = @offset

        = paginate @setlists 

        #setlists  
          .progress
            .indeterminate.light-blue

= javascript_include_tag "music/setlist/stage_setlist", :type=> "text/babel"
     